version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: academy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
