version: '3.8'
services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: academy
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8088:8080
